steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - process_treatment
      - --source=.
      - --trigger-http
      - --runtime=python39
      - --allow-unauthenticated