steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - market-scale-bot
      - --gen1
      - --source=.
      - --entry-point=process_treatment
      - --trigger-http
      - --runtime=python39
      - --allow-unauthenticated
      - --region=europe-west2